name: Publish

on:
  workflow_run:
    workflows: [Unit Tests]
    types: [completed]
    branches: [main]

jobs:
  publish:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup NET6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish to nuget.org
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: MoreRx/MoreRx.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}